import { useState, useCallback } from 'react'

const PLANETS = [
  {
    name: 'Mercury',
    texture: '/2k_mercury.jpg',
    clues: [
      'I am the fastest planet, completing an orbit in just 88 Earth days.',
      'Despite being closest to the Sun, I am not the hottest planet.',
      'I have no atmosphere, so my surface has craters like the Moon.',
      'My surface temperature swings from -180°C to 430°C.',
      'I am the smallest planet in the Solar System.',
    ],
  },
  {
    name: 'Venus',
    texture: '/2k_venus_surface.jpg',
    clues: [
      'I spin backwards compared to most planets — the Sun rises in the west on my surface.',
      'I am completely covered in thick clouds of sulfuric acid.',
      'I am the brightest natural object in the night sky after the Moon.',
      'My surface pressure is 92 times that of Earth — like being 900m underwater.',
      'I am the hottest planet, with temperatures reaching 465°C.',
    ],
  },
  {
    name: 'Earth',
    texture: '/2k_earth_daymap.jpg',
    clues: [
      'I am the densest planet in the Solar System.',
      'I am the only planet not named after a god or goddess.',
      'About 71% of my surface is covered in liquid water.',
      'I have a powerful magnetic field generated by my liquid iron core.',
      'I am the only known world to harbor life.',
    ],
  },
  {
    name: 'Mars',
    texture: '/2k_mars.jpg',
    clues: [
      'I have the largest dust storms in the Solar System, lasting months.',
      'My two moons, Phobos and Deimos, are thought to be captured asteroids.',
      'A day on me lasts 24 hours and 37 minutes — almost the same as Earth.',
      'I have the tallest volcano in the Solar System at 22 km high.',
      'My red color comes from iron oxide — rust — on my surface.',
    ],
  },
  {
    name: 'Jupiter',
    texture: '/2k_jupiter.jpg',
    clues: [
      'My magnetic field is 20,000 times stronger than Earth\'s.',
      'I emit more heat than I receive from the Sun.',
      'I have at least 95 known moons — more than any other planet.',
      'My Great Red Spot is a storm that has lasted over 350 years.',
      'I am so massive that all other planets could fit inside me twice over.',
    ],
  },
  {
    name: 'Saturn',
    texture: '/2k_saturn.jpg',
    clues: [
      'I am the least dense planet — I would float in water.',
      'My rings are made of billions of ice and rock particles.',
      'I have 146 known moons, including Titan which has a thick atmosphere.',
      'My rings span 282,000 km but are only about 10 metres thick.',
      'I am the second largest planet and have the most spectacular ring system.',
    ],
  },
  {
    name: 'Uranus',
    texture: '/2k_uranus.jpg',
    clues: [
      'I was the first planet discovered with a telescope, in 1781.',
      'I radiate almost no internal heat — I am the coldest planetary atmosphere at -224°C.',
      'My rings are vertical because I am tilted on my side.',
      'I rotate on my side with an axial tilt of 98 degrees.',
      'I appear blue-green because of methane in my atmosphere.',
    ],
  },
  {
    name: 'Neptune',
    texture: '/2k_neptune.jpg',
    clues: [
      'I was predicted by mathematics before I was ever observed.',
      'My moon Triton orbits backwards and will eventually be torn apart.',
      'I take 165 Earth years to complete one orbit of the Sun.',
      'My winds reach speeds of 2,100 km/h — the fastest in the Solar System.',
      'I am the farthest planet from the Sun and the smallest of the ice giants.',
    ],
  },
]

function shuffle(arr) {
  const a = [...arr]; for (let i = a.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1));[a[i], a[j]] = [a[j], a[i]] } return a
}

function getHighScores() {
  try { return JSON.parse(localStorage.getItem('astroGuessScores') || '[]') } catch { return [] }
}
function saveHighScore(score) {
  const scores = getHighScores()
  scores.push({ score, date: new Date().toLocaleDateString() })
  scores.sort((a, b) => b.score - a.score)
  const top = scores.slice(0, 10)
  localStorage.setItem('astroGuessScores', JSON.stringify(top))
  return top
}

export default function AstroGuess({ onBack }) {
  const [phase, setPhase] = useState('menu')
  const [planets, setPlanets] = useState([])
  const [current, setCurrent] = useState(0)
  const [cluesShown, setCluesShown] = useState(1)
  const [guess, setGuess] = useState('')
  const [feedback, setFeedback] = useState(null)
  const [score, setScore] = useState(0)
  const [results, setResults] = useState([])
  const [highScores, setHighScores] = useState(getHighScores())
  const [guessOptions, setGuessOptions] = useState([])
  const [guessed, setGuessed] = useState(false)

  const startGame = useCallback(() => {
    const shuffled = shuffle(PLANETS).slice(0, 5)
    setPlanets(shuffled)
    setCurrent(0)
    setCluesShown(1)
    setGuess('')
    setFeedback(null)
    setScore(0)
    setResults([])
    setGuessed(false)
    makeOptions(shuffled, 0)
    setPhase('playing')
  }, [])

  function makeOptions(pList, idx) {
    const correct = pList[idx].name
    const others = shuffle(PLANETS.map(p => p.name).filter(n => n !== correct)).slice(0, 3)
    setGuessOptions(shuffle([correct, ...others]))
  }

  function handleRevealClue() {
    if (cluesShown < 5) setCluesShown(c => c + 1)
  }

  function handleGuess(name) {
    if (guessed) return
    setGuess(name)
    setGuessed(true)
    const planet = planets[current]
    const correct = name === planet.name
    const points = correct ? Math.max(10, (6 - cluesShown) * 40) : 0
    const newScore = score + points
    setScore(newScore)
    setFeedback({ correct, points, answer: planet.name })
    setResults(r => [...r, { planet: planet.name, correct, cluesUsed: cluesShown, points }])
  }

  function handleNext() {
    if (current + 1 >= planets.length) {
      const updated = saveHighScore(score)
      setHighScores(updated)
      setPhase('result')
    } else {
      const next = current + 1
      setCurrent(next)
      setCluesShown(1)
      setGuess('')
      setFeedback(null)
      setGuessed(false)
      makeOptions(planets, next)
    }
  }

  if (phase === 'menu') return (
    <div style={s.root}>
      <button style={s.backBtn} onClick={onBack}>← Games</button>
      <div style={s.menuBox}>
        <div style={s.icon}>🔭</div>
        <h1 style={s.title}>Astro Guess</h1>
        <p style={s.subtitle}>Read the clues one by one. The fewer clues you need, the more points you earn. Maximum 200 points per planet.</p>
        <div style={s.pointsGuide}>
          <div style={s.pgRow}><span>1 clue</span><span style={{ color: '#ffcc44' }}>200 pts</span></div>
          <div style={s.pgRow}><span>2 clues</span><span style={{ color: '#ffcc44' }}>160 pts</span></div>
          <div style={s.pgRow}><span>3 clues</span><span style={{ color: '#ffcc44' }}>120 pts</span></div>
          <div style={s.pgRow}><span>4 clues</span><span style={{ color: '#ffcc44' }}>80 pts</span></div>
          <div style={s.pgRow}><span>5 clues</span><span style={{ color: '#ffcc44' }}>40 pts</span></div>
          <div style={s.pgRow}><span>Wrong</span><span style={{ color: '#ff6666' }}>0 pts</span></div>
        </div>
        <button style={s.startBtn} onClick={startGame}>Start Game</button>
        {highScores.length > 0 && (
          <div style={s.scoresBox}>
            <div style={s.scoresTitle}>🏆 High Scores</div>
            {highScores.slice(0, 5).map((hs, i) => (
              <div key={i} style={s.scoreRow}>
                <span style={s.scoreRank}>#{i + 1}</span>
                <span style={s.scoreVal}>{hs.score} pts</span>
                <span style={s.scoreDate}>{hs.date}</span>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  )

  if (phase === 'result') return (
    <div style={s.root}>
      <button style={s.backBtn} onClick={onBack}>← Games</button>
      <div style={s.menuBox}>
        <div style={s.icon}>🏆</div>
        <h1 style={s.title}>Round Complete</h1>
        <div style={s.finalScore}>{score} <span style={{ fontSize: '1.5rem', color: 'rgba(160,185,255,0.5)' }}>pts</span></div>
        <div style={{ width: '100%', display: 'flex', flexDirection: 'column', gap: '10px' }}>
          {results.map((r, i) => (
            <div key={i} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: 'rgba(8,12,40,0.6)', border: `1px solid ${r.correct ? 'rgba(34,204,136,0.3)' : 'rgba(255,68,68,0.3)'}`, borderRadius: '10px', padding: '14px 18px' }}>
              <span style={{ color: r.correct ? '#22cc88' : '#ff6666', fontSize: '1rem' }}>{r.correct ? '✓' : '✗'}</span>
              <span style={{ color: '#ddeaff', fontSize: '0.9rem' }}>{r.planet}</span>
              <span style={{ color: 'rgba(160,185,255,0.5)', fontSize: '0.8rem' }}>{r.cluesUsed} clue{r.cluesUsed > 1 ? 's' : ''}</span>
              <span style={{ color: '#ffcc44', fontSize: '0.9rem', fontWeight: 500 }}>{r.points} pts</span>
            </div>
          ))}
        </div>
        <div style={{ display: 'flex', gap: '12px' }}>
          <button style={s.startBtn} onClick={startGame}>Play Again</button>
          <button style={{ ...s.startBtn, background: 'transparent', borderColor: 'rgba(100,140,255,0.3)', color: '#99bbff' }} onClick={onBack}>← Games</button>
        </div>
      </div>
    </div>
  )

  const planet = planets[current]

  return (
    <div style={s.root}>
      <div style={s.topBar}>
        <button style={s.backBtn} onClick={() => setPhase('menu')}>✕</button>
        <span style={s.qCount}>Planet {current + 1} / {planets.length}</span>
        <span style={s.scorePill}>⭐ {score}</span>
      </div>
      <div style={s.gameBox}>
        <div style={s.cluesSection}>
          <div style={s.cluesLabel}>Clues revealed: {cluesShown} / 5</div>
          {planet.clues.slice(0, cluesShown).map((clue, i) => (
            <div key={i} style={{ ...s.clueCard, opacity: i === cluesShown - 1 ? 1 : 0.6 }}>
              <span style={s.clueNum}>{i + 1}</span>
              <span style={s.clueText}>{clue}</span>
            </div>
          ))}
          {!guessed && cluesShown < 5 && (
            <button style={s.revealBtn} onClick={handleRevealClue}>Reveal next clue (-{(5 - cluesShown) * 40 - (5 - cluesShown - 1) * 40} pts)</button>
          )}
        </div>
        <div style={s.guessSection}>
          <div style={s.guessLabel}>Which planet is this?</div>
          <div style={s.optGrid}>
            {guessOptions.map(opt => {
              let bg = 'rgba(8,12,40,0.8)', border = 'rgba(80,110,200,0.2)', color = 'rgba(200,220,255,0.85)'
              if (guessed) {
                if (opt === planet.name) { bg = 'rgba(34,204,136,0.15)'; border = '#22cc88'; color = '#22cc88' }
                else if (opt === guess && opt !== planet.name) { bg = 'rgba(255,68,68,0.15)'; border = '#ff4444'; color = '#ff4444' }
              }
              return (
                <button key={opt} disabled={guessed} onClick={() => handleGuess(opt)}
                  style={{ background: bg, border: `1px solid ${border}`, color, borderRadius: '10px', padding: '14px 18px', cursor: guessed ? 'default' : 'pointer', fontSize: '0.9rem', fontFamily: 'inherit', transition: 'all 0.25s' }}>
                  {opt}
                </button>
              )
            })}
          </div>
          {feedback && (
            <div style={{ ...s.feedbackBox, borderColor: feedback.correct ? 'rgba(34,204,136,0.4)' : 'rgba(255,68,68,0.4)', background: feedback.correct ? 'rgba(34,204,136,0.08)' : 'rgba(255,68,68,0.08)' }}>
              <div style={{ color: feedback.correct ? '#22cc88' : '#ff6666', fontSize: '1.1rem', fontWeight: 500 }}>{feedback.correct ? `+${feedback.points} points!` : `The answer was ${feedback.answer}`}</div>
              <button style={s.nextBtn} onClick={handleNext}>{current + 1 >= planets.length ? 'See Results →' : 'Next Planet →'}</button>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

const s = {
  root: { minHeight: '100vh', background: '#02030f', fontFamily: 'Inter, system-ui, sans-serif', display: 'flex', flexDirection: 'column', alignItems: 'center', padding: '0 24px 60px' },
  backBtn: { alignSelf: 'flex-start', marginTop: '24px', background: 'transparent', border: '1px solid rgba(100,140,255,0.25)', color: 'rgba(180,200,255,0.7)', padding: '8px 16px', borderRadius: '8px', cursor: 'pointer', fontSize: '0.82rem', fontFamily: 'inherit' },
  menuBox: { display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '20px', maxWidth: '520px', width: '100%', marginTop: '40px' },
  icon: { fontSize: '4rem' },
  title: { color: '#fff', fontSize: 'clamp(1.8rem,4vw,2.8rem)', fontFamily: 'Georgia, serif', fontWeight: 300, margin: 0, textAlign: 'center' },
  subtitle: { color: 'rgba(160,185,255,0.6)', fontSize: '0.88rem', textAlign: 'center', lineHeight: 1.6, margin: 0 },
  pointsGuide: { width: '100%', background: 'rgba(8,12,40,0.6)', border: '1px solid rgba(80,110,200,0.15)', borderRadius: '12px', padding: '16px 20px', display: 'flex', flexDirection: 'column', gap: '8px' },
  pgRow: { display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem', color: 'rgba(180,200,255,0.6)' },
  startBtn: { background: 'rgba(255,102,34,0.2)', border: '1px solid rgba(255,102,34,0.5)', color: '#ffaa88', padding: '14px 40px', borderRadius: '10px', cursor: 'pointer', fontSize: '1rem', fontFamily: 'inherit', letterSpacing: '0.06em' },
  scoresBox: { width: '100%', background: 'rgba(8,12,40,0.6)', border: '1px solid rgba(80,110,200,0.15)', borderRadius: '14px', padding: '20px 24px' },
  scoresTitle: { color: '#aac4ff', fontSize: '0.85rem', letterSpacing: '0.1em', marginBottom: '14px' },
  scoreRow: { display: 'flex', justifyContent: 'space-between', padding: '8px 0', borderBottom: '1px solid rgba(80,110,200,0.08)' },
  scoreRank: { color: 'rgba(120,160,255,0.5)', fontSize: '0.8rem', width: '28px' },
  scoreVal: { color: '#ddeaff', fontSize: '0.9rem', fontWeight: 500 },
  scoreDate: { color: 'rgba(120,160,255,0.4)', fontSize: '0.75rem' },
  finalScore: { color: '#fff', fontSize: '4rem', fontFamily: 'Georgia, serif', fontWeight: 300 },
  topBar: { width: '100%', maxWidth: '800px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '20px 0 24px' },
  qCount: { color: 'rgba(160,185,255,0.5)', fontSize: '0.8rem', letterSpacing: '0.08em' },
  scorePill: { color: '#ddeaff', fontSize: '0.85rem', background: 'rgba(80,110,200,0.15)', padding: '4px 12px', borderRadius: '20px', border: '1px solid rgba(100,140,255,0.2)' },
  gameBox: { width: '100%', maxWidth: '800px', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '24px' },
  cluesSection: { display: 'flex', flexDirection: 'column', gap: '12px' },
  cluesLabel: { color: 'rgba(120,160,255,0.5)', fontSize: '0.75rem', letterSpacing: '0.1em', textTransform: 'uppercase' },
  clueCard: { background: 'rgba(8,12,40,0.8)', border: '1px solid rgba(80,110,200,0.2)', borderRadius: '10px', padding: '14px 16px', display: 'flex', gap: '12px', alignItems: 'flex-start', transition: 'opacity 0.3s' },
  clueNum: { color: 'rgba(120,160,255,0.5)', fontSize: '0.8rem', flexShrink: 0, marginTop: '2px' },
  clueText: { color: 'rgba(200,220,255,0.85)', fontSize: '0.88rem', lineHeight: 1.6 },
  revealBtn: { background: 'transparent', border: '1px dashed rgba(100,140,255,0.3)', color: 'rgba(160,185,255,0.6)', borderRadius: '8px', padding: '10px 16px', cursor: 'pointer', fontSize: '0.82rem', fontFamily: 'inherit', textAlign: 'center' },
  guessSection: { display: 'flex', flexDirection: 'column', gap: '16px' },
  guessLabel: { color: '#fff', fontSize: '1rem', fontFamily: 'Georgia, serif' },
  optGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px' },
  feedbackBox: { border: '1px solid', borderRadius: '12px', padding: '16px 20px', display: 'flex', flexDirection: 'column', gap: '12px', alignItems: 'flex-start' },
  nextBtn: { background: 'rgba(100,140,255,0.15)', border: '1px solid rgba(100,140,255,0.3)', color: '#aabbff', padding: '10px 20px', borderRadius: '8px', cursor: 'pointer', fontSize: '0.85rem', fontFamily: 'inherit' },
}
