export const LANGUAGES = [
  { code: 'en',  name: 'English',           dir: 'ltr' },
  { code: 'fa',  name: 'فارسی',             dir: 'rtl' },
  { code: 'es',  name: 'Español',           dir: 'ltr' },
  { code: 'fr',  name: 'Français',          dir: 'ltr' },
  { code: 'it',  name: 'Italiano',          dir: 'ltr' },
  { code: 'ca',  name: 'Català',            dir: 'ltr' },
  { code: 'qu',  name: 'Quechua',           dir: 'ltr' },
  { code: 'de',  name: 'Deutsch',           dir: 'ltr' },
  { code: 'nl',  name: 'Nederlands',        dir: 'ltr' },
  { code: 'haw', name: 'ʻŌlelo Hawaiʻi',   dir: 'ltr' },
  { code: 'ar',  name: 'العربية',           dir: 'rtl' },
  { code: 'tr',  name: 'Türkçe',            dir: 'ltr' },
  { code: 'ku',  name: 'Kurdî',             dir: 'rtl' },
  { code: 'ko',  name: '한국어',             dir: 'ltr' },
  { code: 'ja',  name: '日本語',             dir: 'ltr' },
  { code: 'zh',  name: '中文',              dir: 'ltr' },
  { code: 'pt',  name: 'Português (BR)',    dir: 'ltr' },
  { code: 'he',  name: 'עברית',             dir: 'rtl' },
  { code: 'el',  name: 'Ελληνικά',          dir: 'ltr' },
  { code: 'th',  name: 'ภาษาไทย',           dir: 'ltr' },
  { code: 'tl',  name: 'Tagalog',           dir: 'ltr' },
  { code: 'vi',  name: 'Tiếng Việt',        dir: 'ltr' },
  { code: 'hi',  name: 'हिन्दी',             dir: 'ltr' },
  { code: 'ga',  name: 'Gaeilge',           dir: 'ltr' },
  { code: 'ru',  name: 'Русский',           dir: 'ltr' },
  { code: 'pl',  name: 'Polski',            dir: 'ltr' },
  { code: 'ur',  name: 'اردو',              dir: 'rtl' },
  { code: 'zu',  name: 'IsiZulu',           dir: 'ltr' },
  { code: 'hy',  name: 'Հայերեն',           dir: 'ltr' },
  { code: 'iu',  name: 'ᐃᓄᒃᑎᑐᑦ',           dir: 'ltr' },
]
